import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
// import "bootstrap/dist/js/bootstrap.bundle.min.js";
import 'bootstrap-icons/font/bootstrap-icons.css';
import "./globals.css";
import CarouselInit from "@/components/carousel/CarouselInit ";
import Footer from "@/components/common/Footer";
import SideBarMenus from "@/components/common/SideBarMenus";
import NavBar from "@/components/common/NavBar";
import Wrapper from "@/container/Wrapper";
import { AuthProvider } from "@/lib/authProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Super Saving Market",
  description: "Generated by create next app",
  icons: {
    icon: "Favicon.png",                // main favicon
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} "bg-light"`}>

        <AuthProvider>
          <div className="dashboard-container container-fluid py-3">
            <Wrapper>
              <NavBar />
              <SideBarMenus />
            </Wrapper>

            {children}

            <Wrapper>
              <Footer />
            </Wrapper>
          </div>

          <CarouselInit />
        </AuthProvider>


        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
          integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossOrigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
          integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossOrigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossOrigin="anonymous"></script>

      </body>
    </html >
  );
}
