import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
// import "bootstrap/dist/js/bootstrap.bundle.min.js";
import 'bootstrap-icons/font/bootstrap-icons.css';
import "./globals.css";


import CarouselInit from "./components/carousel/CarouselInit ";
import NavBar from "./components/common/NavBar";
import SideBarMenus from "./components/common/SideBarMenus";
import Footer from "./components/common/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Super Saving Market",
  description: "Generated by create next app",
  icons: {
    icon: "Favicon.png",                // main favicon
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} "bg-light"`}>
        <div className="dashboard-container container-fluid py-3">
          <div className="mx-auto inner-dashboard">
            <NavBar/>
            <SideBarMenus/>
            {children}
            
          </div>
<Footer/>
        </div>

        <CarouselInit />
      </body>
    </html>
  );
}
